### ISSUE TITLE
Issues with script recognizing libraries

### ISSUE THREAD

**Issue by ContinualDissapointment** [Rasmusb94/ElevenlabsTTSBot#3]
```
Traceback (most recent call last):
  File "C:\Users\REDCATED\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\REDCATED\ElevenlabsTTSBot\ElevenlabsTTSBot\bot.py", line 397, in _voices
    data = voices()
           ^^^^^^^^
TypeError: 'module' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\REDCATED\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\REDCATED\ElevenlabsTTSBot\ElevenlabsTTSBot\bot.py", line 526, in on_command_error
    raise error
  File "C:\Users\REDCATED\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\REDCATED\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\REDCATED\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'module' object is not callable
```
I've tried following the installation on two different Windows machines. One with a standard python that has env variables set and another which was utilizing pyenv. I'm currently working on testing to see if this issue happens on Debian, I can see the libraries in the scripts directories so I am unsure why the Call is failing.

EDIT: I found that by rolling back to a build of ElevenLabs library dated to when this was last updated I was able to get the modules to be recognized. Specifically 0.2.23.
`
pip install --force-reinstall -v "elevenlabs==0.2.23
`

**Comment by Rasmusb94** [comment]
There was an update to the elevenlabs API, issue is fixed in version 1.1
